apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub 
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.7.1  #192.168.10.123/cloudwalk/selenium-hub:1.0.0 #192.168.10.123/cloudwalk/hub:2.53.0
        ports:
          - containerPort: 4444 
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 30
