apiVersion: v1
kind: Service
metadata:
  labels:
    name: redise-svc
    role: service
  name: redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 36379
  selector:
    name: redis
