apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: redis
        role: server
    spec:
      containers:
      - name: redis
        image: redis:4.0
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
