apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-service
  name: redis-service
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 36379
  selector:
    name: redis
    role: server
