apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: gerrit 
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: gerrit  
    spec:  
      containers:  
      - name: gerrit  
        image: gerritcodereview/gerrit:3.0.2 
        imagePullPolicy: IfNotPresent  
#        resources:
#          limits:
#            cpu: 256m
#            memory: 256Mi
#          requests:
#            cpu: 256m
#            memory: 256Mi
        ports:  
        - containerPort: 8080 
          name: http
          protocol: TCP
        - containerPort: 29418
          name: ssh
          protocol: TCP
        env:
        - name: CANONICAL_WEB_URL
          value: http://localhost
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:  
        - name: git  
          mountPath: /var/gerrit/git
        - name: index
          mountPath: /var/gerrit/index
        - name: cache
          mountPath: /var/gerrit/cache
        - name: etc
          mountPath: /var/gerrit/etc
        - name: db
          mountPath: /var/gerrit/db
      volumes:  
      - name: git
        nfs:  
          server: 192.168.17.11 
          path: "/home/public/gerrit/git" 
      - name: index
        nfs:
          server: 192.168.17.11
          path: "/home/public/gerrit/index"
      - name: cache
        nfs:
          server: 192.168.17.11
          path: "/home/public/gerrit/cache"
      - name: etc
        nfs:
          server: 192.168.17.11
          path: "/home/public/gerrit/etc"
      - name: db
        nfs:
          server: 192.168.17.11
          path: "/home/public/gerrit/db"
