kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: gerrit 
  name: gerrit  
spec:  
  type: NodePort
  ports:  
  - port: 8080
    targetPort: 8080
    name: http  
  - port: 29418
    targetPort: 29418
    name: gerrit
  selector:  
    app: gerrit 
