apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: jenkins  
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: jenkins  
    spec:  
      containers:  
      - name: jenkins  
        image: jenkins/jenkins:2.195 
        imagePullPolicy: IfNotPresent  
#        resources:
#          limits:
#            cpu: 256m
#            memory: 256Mi
#          requests:
#            cpu: 256m
#            memory: 256Mi
        ports:  
        - containerPort: 8080  
          name: web  
          protocol: TCP
        - containerPort: 50000  
          name: agent  
          protocol: TCP
        volumeMounts:  
        - name: jenkinshome  
          mountPath: /var/jenkins_home  
        env:  
        - name: JAVA_OPTS  
          value: "-Duser.timezone=Asia/Shanghai -Dhudson.model.DirectoryBrowserSupport.CSP="  
        - name: TZ
          value: Asia/Shanghai
      volumes:  
      - name: jenkinshome  
        nfs:  
          server: 192.168.17.11  
          path: "/home/public/jenkins" 
