apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: nexus 
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: nexus 
    spec:  
      containers:  
      - name: nexus  
        image: sonatype/nexus:oss 
        imagePullPolicy: IfNotPresent  
#        resources:
#          limits:
#            cpu: 256m
#            memory: 256Mi
#          requests:
#            cpu: 256m
#            memory: 256Mi
        ports:  
        - containerPort: 8081  
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Asia/Shanghai 
        volumeMounts:  
        - name: nexushome  
          mountPath: /sonatype-work  
      volumes:  
      - name: nexushome  
        nfs:
          server: 192.168.17.11 
          path: "/home/public/nexus"
