kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: phpldapadmin 
  name: phpldapadmin  
spec:  
  type: NodePort
  ports:  
  - port: 443
    targetPort: 443
    name: https  
  selector:  
    app: phpldapadmin 
