apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: sonarqube 
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: sonarqube  
    spec:  
      containers:  
      - name: sonarqube  
        image: sonarqube:6.7.3 
        imagePullPolicy: IfNotPresent  
#        resources:
#          limits:
#            cpu: 256m
#            memory: 256Mi
#          requests:
#            cpu: 256m
#            memory: 256Mi
        ports:  
        - containerPort: 9000 
          name: http
          protocol: TCP
        - containerPort: 9092
          name: ssh
          protocol: TCP
        env:
        - name: SONARQUBE_JDBC_URL
          value: jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&useSSL=false&skip-name-resolve=true
        - name: SONARQUBE_JDBC_USERNAME
          value: "root"
        - name: SONARQUBE_JDBC_PASSWORD
          value: "123456"
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:  
        - name: config
          mountPath: /opt/sonarqube/conf
        - name: data
          mountPath: /opt/sonarqube/data
        - name: extensions
          mountPath: /opt/sonarqube/extensions
        - name: plugins
          mountPath: /opt/sonarqube/lib/bundled-plugins
      volumes:  
      - name: config
        nfs:  
          server: 192.168.17.11 
          path: "/home/public/sonarqube/config" 
      - name: data
        nfs:
          server: 192.168.17.11
          path: "/home/public/sonarqube/data"
      - name: extensions
        nfs:
          server: 192.168.17.11
          path: "/home/public/sonarqube/extensions"
      - name: plugins
        nfs:
          server: 192.168.17.11
          path: "/home/public/sonarqube/bundled-plugins"
