kind: Service
apiVersion: v1
metadata:
  labels:
      app: hubot
  name: matterbot
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 38088
    name: hubot
  type: NodePort
  selector:
    k8s-app: hubot
