apiVersion: v1
kind: Service
metadata:
  name: hygieia-ui
  labels:
    name: hygieia-ui-svc
    app: hygieia
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 13380
  type: NodePort
  selector:
    role: hygieia-ui
