apiVersion: v1
kind: Service
metadata:
  name: jitsi-service
  labels:
    app: jitsi
spec:
  ports:
    - name: http
      port: 443
      targetPort: http
      nodePort: 38443
      protocol: TCP
  type: NodePort
  selector:
    app: jitsi
