kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: apidemo 
  name: apidemo  
spec:  
  type: NodePort
  ports:  
  - port: 8000  
    nodePort: 8000
    name: web  
  selector:  
    app: apidemo 
