kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: gitlab 
  name: gitlab  
spec:  
  type: NodePort
  ports:  
  - port: 80
    targetPort: 80
    name: http  
  - port: 22
    targetPort: 22
    name: ssh
  - port: 443
    targetPort: 443
    name: https
  selector:  
    app: gitlab 
