apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: gitlab 
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: gitlab  
    spec:  
      containers:  
      - name: gitlab  
        image: gitlab/gitlab-ce 
        imagePullPolicy: IfNotPresent  
        ports:  
        - containerPort: 80 
          name: http
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:  
        - name: data  
          mountPath: /var/opt/gitlab
        - name: log
          mountPath: /var/log/gitlab
        - name: config
          mountPath: /etc/gitlab
      volumes:  
      - name: config  
        nfs:  
          server: 172.16.33.177 
          path: "/opt/public/gitlab/config" 
      - name: log
        nfs:
          server: 172.16.33.177
          path: "/opt/public/gitlab/log"
      - name: data
        nfs:
          server: 172.16.33.177
          path: "/opt/public/gitlab/data"
