kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: gogs 
  name: gogs  
spec:  
  type: NodePort
  ports:  
  - port: 3000  
    nodePort: 33000
    name: web  
  selector:  
    app: gogs 
