apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gogs
spec:
  serviceName: "gogs"
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: gogs
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage" #此处引用classname
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi 
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - name: gogs
        image: gogs/gogs
        imagePullPolicy: IfNotPresent  
        ports:  
        - containerPort: 3000
          name: web  
          protocol: TCP
        volumeMounts:  
        - name: gogs
          mountPath: /data
