apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jenkins
spec:
  serviceName: "jenkins"
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: jenkins
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage" #此处引用classname
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi 
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins
        imagePullPolicy: IfNotPresent  
        ports:  
        - containerPort: 8080  
          name: web  
          protocol: TCP
        - containerPort: 50000  
          name: agent  
          protocol: TCP
        volumeMounts:  
        - name: jenkins  
          mountPath: /var/jenkins_home  
        env:  
        - name: JAVA_OPTS  
          value: "-Duser.timezone=Asia/Shanghai -Dhudson.model.DirectoryBrowserSupport.CSP="  
