apiVersion: v1
kind: ReplicationController
metadata:
  name: sonar
spec:
  replicas: 1
  selector:
    app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonar
        image: sonarqube:6.6
        ports:
        - containerPort: 9000
          name: sonar
          protocol: TCP
        - containerPort: 9092
          name: agent
          protocol: TCP
        volumeMounts:
        - name: sonardata
          mountPath: /opt/sonarqube/data
        - name: sonarextensions
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: sonardata
        nfs:
          server: 10.10.10.14
          path: "/home/public/sonar/data"
      - name: sonarextensions
        nfs:
          server: 10.10.10.14
          path: "/home/public/sonar/extensions"
