apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 9000
    name: sonar
  - port: 9092
    targetPort: 9092
    nodePort: 9092
    name: agent
  type: NodePort
  selector:
    app: sonar
