apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb
        app: hygieia
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
      volumes:
      - name: mongodb
        nfs:
          server: 192.168.17.11
          path: /home/public/mongodb
