apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        app: hygieia
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: 192.168.10.123/pass/mongodb:3.5
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        nfs:
          server: 192.168.10.123
          path: /home/public/pass/mongodb
