apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    k8s-app: postgredb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        k8s-app: postgredb
    spec:
      containers:
      - name: postgres
        image: postgres:9
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres.env
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres.env
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.env
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        glusterfs:
          endpoints: glusterfs-cluster
          path: postgres-mm-disk
          readOnly: false
