apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: postgres
  name: pgdb
  namespace: default
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    k8s-app: postgredb
