apiVersion: v1
kind: Service
metadata:
  name: mmwebrtcsvc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 7088
    nodePort: 7088
    name: adminport
  - port: 7089
    nodePort: 7089
  - port: 8189
    nodePort: 8189
    name: websocket
  - port: 8188
    nodePort: 8188
  selector:
    app: webrtc
